theme: jekyll-theme-slate
title: Global ACEP database
description: The BIC operates the Global ACEP Database under the guidance of the International Maritime Organization (IMO), which has encouraged all National Administrations to utilize the database for the publication of their ACEPs (see CSC.1/CIRC.143 and CSC.1/CIRC.138/REV.1).
